### PR TITLE
Provide option for only showing historical changes

### LINKED ISSUE #69: Only show changes in history view
Currently the history view we have shows every record we have. We should simplify this and make it so that only changes are shown.

### PR DESCRIPTION
**Pull request by AetherUnbound**
This PR changes the behavior of the historical view so that the page only displays changes to the history (rather than the whole history). In order to maintain previous functionality, I've added a button which allows viewing the full history across all rosters.

I also changed the file types of some jinja templates we had to be consistent across the board (and also let my IDE recognize them as HTML).

https://user-images.githubusercontent.com/10214785/147322646-29b22fc1-1fde-449a-a5ba-06cad969d474.mp4

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
Nice! I'm not a big fan of using filters like this, I think I'd prefer the filtering of the records to happen before we call `render_template` instead of adding the logic to the template, but it definitely works 🎉 I tested with `/historical-officers/DV39?show_full_history=true` and that badge shows both versions working perfectly. Badge's with just a single record also appear to work. I couldn't find one that has multipl records with no changes so I couldn't test that but I don't see why it wouldn't work.

**Comment by AetherUnbound** [comment]
Oh dang, that seems like it'd be a way better approach 😂🤦🏼‍♀️ chalk that up to watching bachelorette while I worked on this haha. I'll try to see if I can move that logic out of the template.

**Comment by AetherUnbound** [comment]
@sarayourfriend does that seem better? I feel like it's more complicated this way but I'm not an objective third party :thinking:

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Comment by sarayourfriend** [comment]
I think it's simpler out of the template (for one it should be easier to find where this is happening in the future I think?). I suppose having to check `historical` makes it slightly more complicated but I'm wishing we'd separated that route out a little more but 😬 I don't think it's a the point that it would justify refactoring all of that just to accomodate this change more cleanly.

**Pull request merged**
